
# You can find more wallpapers in ~/.config/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing to another wallpaper
preload = ~/wallpapers/1549126.jpg
wallpaper = ,~/wallpapers/1549126.jpg 
splash = false
