# You can find more wallpapers in ~/.config/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing to another wallpaper
preload = ~/wallpapers/cyberpunk-2077-2560x1440-12862.png
wallpaper = ,~/wallpapers/cyberpunk-2077-2560x1440-12862.png
splash = false
