#+HUGO_BASE_DIR: /home/kimnux/Homepage
#+HUGO_SECTION: post
#+TITLE: hugo로 github에 블로그 올리기
#+LANGUGE: en
#+AUTHOR: "kimnux"
#+EMAIL : "kimnux@gmail.com"
#+DATE : 2024-07-07
#+TAGS: hugo github
#+OPTIONS: toc:nil

* hugo 프로젝트 만들기
#+begin_src bash
hugo new site kimnux12.github.io
#+end_src
* 테마 다운받기
** ~/kimnux12.github.io/themes로 이동
#+begin_src bash
cd kimnux12.github.io/themes

git clone https://github.com/chipzoller/hugo-clarity.git

cd hugo-clarity

rm -rf .git
#+end_src
** ~/kimnux12.github.io/에 있는 config.toml 또는 hugo.toml을 열어
  - theme = "hugo-clarity" 추가
  - baseUrl = 'kimnux12.github.io' 변경. 만약 고치지 않으면 홈페이지가 깨져서 표시된다.
* 새 문서 생성하기
~/kimnux.github.io 폴더에서
#+begin_src bash
hugo new post/test.md
#+end_src
* hugo서버 실행 미리보기
#+begin_src bash
hugo server -D
#+end_src
브라우저에 http://localhost:1313 입력 후 접속해서 제대로 뜨는지 확인
* orphan branch 제작
hugo는 kimnux12.github.io를 통으로 올릴 저장소와 public 폴더를 올릴 저장소가 따로 필요하단다.
** 전체 폴더를 올릴 저장소 만들기
기존에 사용 중이던 https://github.com/kimnux12/dotfile.git에 고아브랜치를 만들어서 올릴 생각이다.
~/kimnux12.github.io/로 이동 후
#+begin_src bash
git init

git remote add origin https://github.com/kimnux12/dotfile.git
# 혹시 원격 저장소 이름을 잘못 입력하였다면(origin인데 orogin으로 입력하는 등..)
# git remote rename orogin origin
git checkout --orphan hugo #hugo는 orphan branch

git rm -rf . # 안해도 됨. 새로운 orphan branch를 깨끗한 상태로 시작하려는 것.
#+end_src
** public 폴더를 첫번째 저장소의 submodule로 만들기
#+begin_src bash
rm -rf public

git submodule add -b master https://github.com/kimnux12/kimnux12.github.io.git public
#+end_src
* 빌드하기
#+begin_src bash
hugo -t hugo-clarity
#+end_src
빌드를 하면 public폴더가 생기는데 이 public폴더를 kimnux12.github.io.git에 올리면
홈페이지로 작동하게 된다.
* public 폴더 저장소에 올리기
어느 것부터 올리느냐는 상관없다.
#+begin_src bash
cd public

git add .

git commit -m "message"

git push origin master
#+end_src
* 전체 폴더 저장소에 올리기
#+begin_src bash
cd ..

git config --global user.name kimnux12

git config --global user.email kimnux@gmail.com

git add .

git commit -m "message"

git push origin hugo
#+end_src

* git submodule 지정한 후 submodule의 원격저장소를 지우고 싶을 때
~/kimnux.github.io 디렉토리로 들어간 후
** 서브모듈 초기화
#+begin_src bash
git submodule init
#+end_src
** 서브모듈 업데이트
#+begin_src bash
git submodule update
#+end_src
** 서브모듈에서 master 브랜치로 전환
#+begin_src bash
cd public
git checkout master
#+end_src
** 모든 파일 삭제
#+begin_src bash
git rm -rf .
#+end_src
** 변경 사항 커밋
#+begin_src bash
git commit -m "Remove all files from master branch"
#+end_src
** 변경 사항을 원격저장소에 푸시
#+begin_src bash
git push origin master
#+end_src
